"""
Golden tests for the fpy compiler.

These tests compile simple fpy programs and compare the generated bytecode
against expected output stored in golden files.

Golden files are stored in test/fpy/golden/ with:
- <name>.fpy: The source file to compile
- <name>.fpybc: The expected bytecode output
"""

import pytest
from pathlib import Path

import fpy.error
from fpy.compiler import text_to_ast, analyze_ast, analysis_to_fpybc_directives
from fpy.state import get_base_compile_state
from fpy.bytecode.assembler import fpybc_directives_to_fpyasm

GOLDEN_DIR = Path(__file__).parent / "golden"

# Path to the test dictionary
DEFAULT_DICTIONARY = str(Path(__file__).parent / "RefTopologyDictionary.json")


def compile_to_fpybc(source: str) -> str:
    """Compile fpy source code to fpybc bytecode text."""
    fpy.error.file_name = "<golden-test>"
    fpy.error.input_text = source
    fpy.error.input_lines = source.splitlines()

    state = get_base_compile_state(DEFAULT_DICTIONARY)

    body = text_to_ast(source)

    state = analyze_ast(body, state)
    directives, _ = analysis_to_fpybc_directives(state)
    return fpybc_directives_to_fpyasm(directives)


def get_golden_test_cases():
    """Find all golden test cases (pairs of .fpy and .fpybc files)."""
    if not GOLDEN_DIR.exists():
        return []

    test_cases = []
    for fpy_file in sorted(GOLDEN_DIR.glob("*.fpy")):
        fpybc_file = fpy_file.with_suffix(".fpybc")
        if fpybc_file.exists():
            test_cases.append(fpy_file.stem)
    return test_cases


@pytest.mark.parametrize("test_name", get_golden_test_cases())
def test_golden(test_name: str):
    """
    Golden test: compile the .fpy file and compare against the .fpybc file.
    """
    fpy_file = GOLDEN_DIR / f"{test_name}.fpy"
    fpybc_file = GOLDEN_DIR / f"{test_name}.fpybc"

    source = fpy_file.read_text()
    expected = fpybc_file.read_text()

    actual = compile_to_fpybc(source)

    assert actual == expected, (
        f"Golden test '{test_name}' failed.\n"
        f"Expected:\n{expected}\n"
        f"Actual:\n{actual}\n"
    )


def update_golden(test_name: str):
    """
    Utility to update a golden file. Run manually if needed.
    """
    fpy_file = GOLDEN_DIR / f"{test_name}.fpy"
    fpybc_file = GOLDEN_DIR / f"{test_name}.fpybc"

    source = fpy_file.read_text()
    actual = compile_to_fpybc(source)

    fpybc_file.write_text(actual)
    print(f"Updated {fpybc_file}")


def update_all_golden_seqs():
    """
    Utility to update all golden files. Run manually if needed.
    """
    for fpy_file in sorted(GOLDEN_DIR.glob("*.fpy")):
        test_name = fpy_file.stem
        update_golden(test_name)
